[package]
name = "claripy"
version = "0.1.0"
edition = "2021"

[lib]
name = "clarirs"
crate-type = ["cdylib"]

[dependencies]
md5 = "0.7.0"
pyo3 = { version = "0.22.0", features = ["extension-module"] }
