/**
 * @file
 * @brief This file defines a function to register the manually written API code
 * \ingroup api
 */
#ifndef R_SRC_API_MANUAL_HPP_
#define R_SRC_API_MANUAL_HPP_

#include "constants.hpp"

// TODO: bindings that take time should disengage the GIL. This is really an autogen thing though

namespace API {
    /** Called by our autogen'd API to insert additional non-autogenerated bindings */
    void bind_manual(pybind11::module_ &root_module, Binder::ModuleGetter &m);
} // namespace API

#endif
