#ifndef R_API_MANUAL_HPP_
#define R_API_MANUAL_HPP_

#include <functional>
#include <pybind11/pybind11.h>

namespace API {
    /** Called by our API to insert additional non-autogenerated bindings */
    void bind_manual(pybind11::module_ &m);

} // namespace API

#endif