/**
 * @file
 * \defgroup test_autogen Files autogenerated for unit tests
 * @brief Define constants used across unit tests
 */
#ifndef __TESTS_NATIVE_CONSTANTS_HPP__
#define __TESTS_NATIVE_CONSTANTS_HPP__

namespace UnitTest {

    /** The test function type */
    using Test = int();

} // namespace UnitTest

#endif
