name: Test on Windows

on:
  workflow_dispatch:
  workflow_call:

jobs:
  windows:
    name: Test Windows
    runs-on: windows-2022
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: "3.8"
      - run: python -m venv $HOME/venv
        name: Create venv
        shell: bash
      - run: |
          call %USERPROFILE%\venv\Scripts\activate
          pip install .[testing]
        name: Install
        shell: cmd
      - run: |
          call %USERPROFILE%\venv\Scripts\activate
          pytest -n auto
        name: Run pytest
        shell: cmd
